from setuptools import setup, find_packages

setup(
    name='odoo_etl_pipeline',
    version='0.1.0',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    install_requires=[
        'aiobotocore==2.7.0',
        'aiohttp==3.8.1',
        'pydantic==1.9.1',
        'PyYAML==6.0',
        'apache-airflow==2.7.1',
        'odoo-xmlrpc==3.0',
        'pydantic-settings==2.0.2',
        'loguru==0.7.2',
        'tenacity==8.2.3',
        'pytest==7.4.4',
        'pytest-asyncio==0.23.2',
        'pytest-mock==3.12.0',
        'prometheus_client==0.16.0',
    ],
    author='Your Name',
    author_email='your.email@example.com',
    description='ETL Pipeline for RapidAPI Leads to Odoo CRM',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/yourusername/odoo-etl-pipeline',
    license='MIT',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: ETL',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
    ],
    python_requires='>=3.8',
)
